name: Money2XP
main: tzer0.Money2XP.Money2XP
version: 1.0
author: TZer0
commands:
    m2x:
        description: Allows players to purchase xp for iConomy-money
        usage: /m2x
    m2xtrain:
        description: Configures training-zones
        usage: /m2xtrain
    m2xt:
        description: Configures training-zones
        usage: /m2xt
    m2xset:
        description: Administrates money/xp-settings.
        usage: /m2xset
    m2xs:
        description: Administrates money/xp-settings.
        usage: /m2xs
        
